name: Deploy pkgdown to GitHub Pages

on:
  push:
    branches:
      - main  # Set to default branch of your repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.x'  # Set this to your required version of R

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages("remotes")'
        Rscript -e 'remotes::install_github("r-lib/pkgdown")'

    - name: Build pkgdown site
      run: |
        Rscript -e 'pkgdown::build_site()'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
