name: R Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - name: Install dependencies
      run: |
        install.packages("devtools")
        devtools::install_deps(dependencies = TRUE)
    - name: Check
      run: R CMD build . && R CMD check *tar.gz
