# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'run build')"
    runs-on: macos-latest
    strategy:
      matrix:
         r-version: ['4.1.1']

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      
      - name: Install BasicTeX
        run: |
          brew install --cask basictex
        shell: bash
      
      - name: Add TeX Live to PATH
        run: echo "/usr/local/texlive/2023/bin/universal-darwin/tlmgr" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        
      - name: Build pkgdown site
      run: |
        Rscript -e 'pkgdown::build_site()'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
        
      - name: Install Pandoc
        run: brew install pandoc
  
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
